// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Data;

#nullable disable

namespace Web.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Web.Models.DiaryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Diaries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Without Goal, I have realized that I have nothing to do.",
                            CreatedAt = new DateTime(2024, 10, 11, 15, 22, 10, 729, DateTimeKind.Utc).AddTicks(9380),
                            Title = "Goal",
                            UpdatedAt = new DateTime(2024, 10, 11, 15, 22, 10, 729, DateTimeKind.Utc).AddTicks(9380)
                        },
                        new
                        {
                            Id = 2,
                            Content = "Without love, I have realized that I have nothing to do.",
                            CreatedAt = new DateTime(2024, 10, 11, 15, 22, 10, 729, DateTimeKind.Utc).AddTicks(9390),
                            Title = "Love",
                            UpdatedAt = new DateTime(2024, 10, 11, 15, 22, 10, 729, DateTimeKind.Utc).AddTicks(9390)
                        },
                        new
                        {
                            Id = 3,
                            Content = "Without happiness, I have realized that I have nothing to do.",
                            CreatedAt = new DateTime(2024, 10, 11, 15, 22, 10, 729, DateTimeKind.Utc).AddTicks(9390),
                            Title = "Happiness",
                            UpdatedAt = new DateTime(2024, 10, 11, 15, 22, 10, 729, DateTimeKind.Utc).AddTicks(9390)
                        },
                        new
                        {
                            Id = 4,
                            Content = "Without motivation, I have realized that I have nothing to do.",
                            CreatedAt = new DateTime(2024, 10, 11, 15, 22, 10, 729, DateTimeKind.Utc).AddTicks(9400),
                            Title = "Motivation",
                            UpdatedAt = new DateTime(2024, 10, 11, 15, 22, 10, 729, DateTimeKind.Utc).AddTicks(9400)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
